import type { EssaySection } from './aboutEssay'
import { aboutEssay, aboutEssaySubtitle } from './aboutEssay'

/* On-site long-form pieces, keyed by slug. A note in the Writing section
   shows a blurb and links here; the full text opens in the ReadingOverlay
   (same full-screen reader as the About essay). */
export type Essay = {
  title: string
  subtitle?: string
  sections: EssaySection[]
  sourceNote?: string
}

export const essaysBySlug: Record<string, Essay> = {
  /* Same piece the About section opens, registered here so the Writing
     notes can reach it too. One source of truth in aboutEssay.ts. */
  'how-i-think': {
    title: 'How I Think',
    subtitle: aboutEssaySubtitle,
    sections: aboutEssay,
  },

  'ten-lessons-poseidon-fellowship': {
    title: '10 Lessons from Poseidon Fellows',
    sections: [
      {
        paragraphs: [
          'As I am beginning my final year at UC San Diego, I’d like to reflect on one of the most impactful opportunities I was a part of and leave you with some freshly minted lessons. This past spring I was selected to be 1 of 12 in the inaugural cohort of [Poseidon Fellows](https://today.ucsd.edu/story/poseidon-fellows-first-cohort), a fellowship focused on company building, venture capital and leadership. Under the mentorship of Shawn Xu, partner at [Lowercarbon Capital](https://lowercarbon.com/), and Elizabeth Lyons, associate professor in the [School of Global Policy and Strategy](https://gps.ucsd.edu/), I had the chance to sit down with founders, investors, and the first U.S. Chief Data Scientist.',
          '![Poseidon Fellows Inaugural Cohort](/images/poseidon/inaugural-cohort.jpg)',
          'I entered this fellowship with a clouded sense of direction having sold the business catalog for my automotive detailing business. Around this same time I was weathering the storm of my failed investment thesis that took me through a roller coaster of emotions going from $50K to $500K before losing it all and being $50K in debt to investors around my 20th birthday. I describe this period of my life as the "fog", a deeply transformative time with no compass.',
          'Oftentimes I felt that I was moving in circles and that the "fog" had permanently damaged the sails of my ship. I view Poseidon Fellows as being the mirror that reflected back the greatness I didn’t know I was capable of. I had been operating under self-doubt wearing the costume of realism. Below are my takeaways and reflections I hope serve as inspiration to wherever this finds you.',
        ],
      },
      {
        heading: '1. Careers look like unbroken winning from the outside',
        paragraphs: [
          'It is very easy to zoom out on someone successful and see a run of wins stacked one after the other.',
          'From that distance you lose the struggle, the grind, and the days spent chewing glass. DJ Patil, former U.S. Chief Data Scientist, made this point during his session, and I later found that he had written a sharper version of it years before, in a [2013 post](https://www.linkedin.com/pulse/20130521100832-4933865-class-of-2013-why-i-m-counting-on-you-to-fail/) I would recommend reading.',
          '> You can read all about me in the bio or my LinkedIn profile and you’ll see that I received my Ph.D in Applied Math from here 11 years ago. I’ve worked for the Department of Defense and been to Kazakhstan. But you won’t see all the failures that made up the journey.',
          'What that journey actually contains, [in his telling](https://www.linkedin.com/pulse/20130521100832-4933865-class-of-2013-why-i-m-counting-on-you-to-fail/), is a high school graduation he only reached because a kind administrator took pity on him. What followed was zero college acceptance letters. Years later at Maryland he failed his first graduate class and scored second to last on his first PhD qualifying exam, in what he calls one of the toughest and loneliest years of his life. The next time the qualifiers came round he had the highest scores. Several years after that he would co-coin the title "data scientist" and become the second person ever to ride a skateboard in the White House. By the fifth session I had heard four more versions of these stories, none of which appear in the way these people get introduced.',
          '![DJ Patil & I after dinner](/images/poseidon/dj-and-i.jpg)',
          'The struggle I and almost every student I talk to share is this endless running against versions of other people that do not exist. You are setting your own struggle which you experience in full resolution against somebody else’s highlight reel. Inevitably you will feel like you are failing.',
          'This endless race simply does not exist. It took me long enough to figure out that I was running from a version I was afraid of becoming and running towards a version sold to me. The goal was never to surpass the people around you but to surpass the version of who you were yesterday.',
        ],
      },
      {
        heading: '2. Follow the thread of curiosity and gravitate towards joy',
        paragraphs: [
          'What you do with unclaimed time is the most honest information you have about yourself.',
          'In the first session with Michael Retchin, founder and CEO of a stealth startup, I wanted to push on how a person tells whether the path they are on is the right one. Michael answered by recounting his own, which started with a childhood fascination with computers and programming. His advice was to treat what you keep returning to in your free time as a signal and then to build something structural around it. Shawn put it as a question. After all the Netflix shows have been watched and the distractions consumed, where does your mind go?',
          '![Shawn & I after our end of year dinner](/images/poseidon/shawn-and-i.jpg)',
          'I took up their pragmatic advice and decided to eliminate my distractions. I deleted all social media apps and after an interim of constantly reaching for my phone, old habits I had forgotten about began to emerge. I reflected on what brought me joy and the answer lay in what I created when no one watched. Films I would shoot, monologues I would write, stories I would share late at night with friends. I never committed to developing the habits I loved or to sharing them with others. As I began to film and write more, it has proven to be a guiding force to wherever life takes me.',
          'Although I plan to not have my career centered around writing, this joyful pursuit has proven to be useful in ways I didn’t imagine. It has served as a sandbox for my imagination and a playground to train my articulation. Late night writing sessions have brought me clarity to the path I am navigating and served as physical reminders to where I am headed.',
          'I had assumed that finding direction would mean learning something new about myself, when the whole exercise came down to paying attention to what I had already been doing.',
        ],
      },
      {
        heading: '3. Your perspective is your superpower',
        paragraphs: [
          'I had a habit of discounting my own views and it took someone interrupting me to notice it.',
          'I said something at dinner that I had said a hundred times before. I was talking about public policy when I opened with the phrase, "you know better than I do on this topic." One of the speakers stopped me there and told me never to say it again.',
          'The argument was that I had volunteered away what I was bringing to the table. Your background, your beliefs, and the particular way you see a problem are your strength, and downplaying them in your first six words trains the room to discount whatever follows.',
          'I began to question whether I had been challenging my own beliefs at all, and what it actually takes to have a distinct perspective.',
          '![DJ, Shawn, and fellows after our third session](/images/poseidon/dj-shawn-group.jpg)',
          'Michael Retchin gave me a different outlook. The version you usually hear is to keep a list of your contrarian beliefs. Michael’s take is that the criterion paralyzes people, since you can’t really know what everyone else believes. His version is to keep a running list of what you firmly believe in. Dig far enough into it and the beliefs nobody else holds will surface on their own. You’ll know other people disagree with the beliefs when you present them and they vehemently disagree with you. A belief left unexamined in your head feels far more defensible than it does on a page.',
          'To keep this from becoming stubbornness, it is best to have strong opinions loosely held. You commit to a position hard enough that it can be tested, and you stay willing to be shown wrong. Conviction without revisability is just noise, and revisability without conviction lacks depth.',
          'I have begun keeping note of my contrarian beliefs. The one I am most willing to defend is that business creation is a religious act.',
          'I mean that structurally. You bring something into existence, you stake yourself on a future you cannot verify, and you are answerable to it in a way that never resolves into cost and benefit, all of which are theological categories not commercial ones. If business creation is a religious act then a great deal of it is idolatry, and the god is rarely money. It is usually the founder, and the company is the monument.',
        ],
      },
      {
        heading: '4. There is no playbook',
        paragraphs: [
          'Other people’s past experience can’t tell you what you should do in the present.',
          'For most of my fog I was working constantly and producing nothing. I was always moving toward something but couldn’t tell you what it was. I spent more time asking for advice, curating a list of podcasts, never devoting the time necessary to build up a foundation. It was always easier to start something new, to reach for the next shiny thing, and put off questioning why.',
          '> It is easier to wage a battle against distant abstractions than to fight the quiet war inside one’s own soul.\n— Leo Tolstoy',
          'Part of the fellowship contains office hours with Shawn. There I pushed on how a person is to decide the right move in their career. I expected to walk through some weighing of the options. Instead he asked me what my North Star principles were: what I would live for, die for, stand for and fight for.',
          'Rick Rubin has a great philosophy surrounding this. You have to take the time to know yourself because you are the only audience you actually know. The moment you begin to perform for others you produce a projection rather than an authentic work. A playbook is what I was searching for. It is a telling of what worked for a person whose circumstances were never yours.',
          '![Supporting the fellows at the Undergraduate Engineering Research Symposium](/images/poseidon/research-symposium.jpg)',
          'What I have built since is an operating system. First, inspect the foundation upon which you act. If someone watched your last 30 days without hearing your thoughts, what would you need to unlearn? Your rulebook sits on top of this, a written guide that decides what a day, a week, a month gets spent on. Systems are next, sequences of planned moves that bring you closer to your North Star. Work with no foundation under it is just noise. It rebuilds itself every few weeks until you are spending more time maintaining rather than creating.',
          'The whole purpose of your operating system is to remove friction. Personally, I noticed that my house had no dedicated spaces. This left me negotiating with myself on what needed to be done. To remove the self-negotiation, I recently created sanctuaries: dedicated spaces for deep work, for reading, for leisure.',
          'I am not working any less than I did in the fog. What changed is that I stopped looking for the answer somewhere else and sat down with the questions I had been avoiding.',
        ],
      },
      {
        heading: '5. Learn to sell and to tell a story',
        paragraphs: [
          'Across five sessions the pattern I found most surprising revolved around eloquence.',
          'Every guest speaker would carry you somewhere with their words. They didn’t just answer questions, they told compelling stories that you were a part of.',
          'I asked every speaker the following question: "If you could travel back in time to sit across from your 21 year old self, is there any skill, framework, or advice you wish you would’ve told them?" The responses I heard ranged from sales to cold calling to storytelling.',
          'As they all recounted the path that led them here, I was reminded of this [video](https://youtu.be/GA8z7f7a2Pk?si=sgX0iGdZWpWB-heZ) of a man alone on a hill, dancing shirtless while everyone around decides not to look. After a while alone, one person joins in and suddenly everyone follows. Before the dance party happens, the man on the hill has to be willing to look ridiculous for long enough that somebody else can arrive. The man on the hill has to play the fool.',
          'I reflected on what the speakers told me and noticed that my clarity of expression did not match my clarity of thought. If I were to convince others to play the fool with me, I would have to articulate myself better.',
          '![Lunch talks with the fellows](/images/poseidon/lunch-talks.jpg)',
          'I’ve found in sales that you always have a superpower that is being underutilized. When I started my detailing business at 17, I was selling to people three times my age and while being young is an obstacle when establishing credibility, it became my secret sauce. Being young splits the room into people who want to help a young hustler, people who will at least give you advice, and people who have already decided your product is bad.',
          'Every one of those outcomes returns something. The cost of making the ask is close to nothing and the cost of not doing so is the entire opportunity. Once customers found out that an 18 year old produced a high quality service, they began seeking me out.',
          'This doesn’t apply solely to age. I have found that being a student is the current superpower I possess and try to lean into. When I hustled and flipped sectional couches, the superpower was my truck that could offer free delivery. When I ran my marketing agency the superpower was my recent success in the detailing business. I could show local companies how to make their inbound leads look more like mine.',
        ],
      },
      {
        heading: '6. Mentorship and relationships compound',
        paragraphs: [
          'There are plenty of people who will help you out, most of them just don’t know you exist.',
          'When Michael Retchin spoke to us he mentioned that he had emailed around two hundred people he admired, asking for their input and hoping one of them might become a mentor. Around this time, I put little to no effort in reaching out to ask for help. I viewed it as a declaration of weakness and felt I had no permission to do so.',
          'The great privilege of being a student is that everyone expects you to fail. You are underpromising by default which leaves overdelivering as the one thing available to you. It also means you have been handed an invitation to play the fool. I constantly try to remind myself of the following:',
          '> When you are 20, you care about what everyone thinks. When you are 40, you stop caring about what everyone thinks. When you are 60, you realize no one was ever thinking about you in the first place.',
          '![Poseidon Fellows end of year dinner with Tess Hatch & Jimmy Douglas](/images/poseidon/end-of-year-dinner.jpg)',
          'What I realized is that asking is not extraction. Asking for help creates an opportunity to learn and an opportunity to give. I’ve found that most people want to be useful and are almost never given the chance to be.',
          'When I want further clarity on a decision I am sitting on, I now write down five people who might know the answer and contact all of them. Cold email, cold DM, whatever reaches them. Silence is the outcome I assume going in and it costs me nothing. You’d be surprised how many people reply.',
          'Toward the end of the fellowship we were given office hours with Tess Hatch, Managing Director at Stifel Venture Bank and former partner at Bessemer Venture Partners. She gave me the vocabulary for what happens after that first reply. There are mentors, who give you advice when you reach out. There are champions, who reach out to you. And there are sponsors, who put you into positions unprompted. Her own practice, which she credits to Tina Seelig, is to go through your calendar and send the thanks or the check-in on a regular basis rather than when you need something.',
          'I asked Tess the same question I had asked every speaker, "what would you tell your twenty-one year old self?" She said she would answer it after I read Tina Seelig’s What I Wish I Knew When I Was 20. What she gave me instead of an answer was an invitation to reach out again, and I have been using it since.',
        ],
      },
      {
        heading: '7. Study inflections not outcomes',
        paragraphs: [
          'I have never once changed direction while things were going well.',
          'Inflections came up more than once during the fellowship. The idea comes from Mike Maples Jr., who writes about it [here](https://medium.com/@m2jr/how-inflections-let-startups-change-the-rules-a8cca5f9b948) and in his book Pattern Breakers. The term comes from Andy Grove who used it at Intel to describe a turning point in how people think, what they believe, what they can do, or a change in what they value. He meant it as a warning to incumbents. Maples reads it as an attacker’s advantage, since a startup has nothing to defend and everything to gain when the rules change.',
          'I believe the definition can be applied more personally. There are points on your timeline that change the trajectory of who you are and what you end up becoming.',
          'I count three inflections of mine. Two of them you have already met: my detailing business and my failed investment. The third is the reason you are reading this: the Poseidon Fellowship.',
          '![The Inaugural 12 fellows](/images/poseidon/inaugural-twelve.jpg)',
          'The investment is the one worth showing, because the thinking was not entirely wrong. After the FTX collapse, I was deep enough in the forums to watch Coinbase take significant market share. Base chain had just launched, hype was building around SAB 121’s rescission, and the first ETFs were on the horizon. On Base chain, Aerodrome had become the major DEX providing liquidity. I instinctively went looking for the next tier of protocol nobody was watching. There I found Alienbase, a DEX positioned to benefit from increased on chain volume. I pushed in all my chips and it played out exactly as I had prepared for.',
          'What failed was that I had a thesis and no structure. I told myself I would take chips off the table, not knowing how avaricious I would become. I watched a year erase what I had built and before I knew it, I learned a $550,000 lesson.',
          '> I learned to love the thing that I most wish had not happened.\n— Stephen Colbert',
          'My setback was not an interruption of an inflection. It was one, and the third inflection does not happen without it. I used to be motivated by how impressive my achievements were, not seeing the inflated ego or self-pride I built up. I learned valuable lessons on humility and without this loss, who knows if I would be writing today.',
          'You cannot summon an inflection. What you can do is go backwards, write out the points where your life actually changed direction. Look at what was happening immediately before each one and acknowledge the faults in your thinking. Personally, heartbreak at seventeen turned into the detailing business overnight. An arrogant level of self-pride turned crypto obsession into my investment. The lowest point of my life turned into an application I sent expecting nothing. If the same turns out to be true for you, then the stretch you are in right now is setting up the next turn.',
        ],
      },
      {
        heading: '8. Swing big when quitting is the rational move',
        paragraphs: [
          'The heaviest card stacked against you is your own self-doubt.',
          'The last session was with Jimmy Douglas, founder and CEO of Plug. Jimmy came from being an executive at Tesla where he had a front row seat to the used EV market. At the time, no real EV marketplace existed and what was in place was largely broken. With a problem that was uniquely his, Jimmy left to start Plug around the time his child was born.',
          'What followed was six months without a single car sale and more than fourteen failed go-to-market pivots. Even with a newborn at home Jimmy kept swinging.',
          'Plug had been built to stay balance sheet light and did not buy vehicles directly from consumers, and in 2025 that changed. The year before, Plug had bought from twelve unique sellers. By Q4 of 2025, its sales volume had passed everything the company did in the whole of 2024. Twelve sellers had become more than four hundred, and as of this August that number is over sixteen hundred.',
          '![Working through some problems with a couple fellows](/images/poseidon/working-through-problems.jpg)',
          'Jimmy’s story is an inspirational lesson on tenacity. The facts that make quitting look rational are the same facts that make the swing possible. Every person I met this past spring built during a stretch when stopping would have been a reasonable choice.',
          'I am often reminded of this voice in my head whose only job is to get me to stop. On a run it tells me that my legs hurt badly and stopping now would be reasonable. In a productive week it tells me I should rest, that I have done enough. It is very good at its work, because it never argues with anything I actually believe. It only ever hands me a reason I was already looking for.',
          'The entire discipline is learning to hear this as a voice rather than as information.',
        ],
      },
      {
        heading: '9. Lead with authenticity',
        paragraphs: [
          'In a world that demands performance, the greatest luxury is authenticity.',
          'The full version of who I was, actually present, committed and visible, was never genuinely shown to anyone. Once you have lived performing through academics and achievement, the masks pile up and they get heavy. If you are not genuine to yourself, nothing is there. It all takes the form of a projection. It takes time after you set the masks down to work out what a life without them actually looks like.',
          'This performance costs both sides of the room. The performer never reaches what they are capable of in their true form, and the people watching never get to see it either. Everyone settles for a lesser version of a person that took real effort to produce.',
          'Authenticity is becoming increasingly more valuable. With competence being democratized in front of us, judgment and taste all come from being authentic rather than a polished performance. This can also be seen socially. Every public self has been optimized, and the scarce thing now is somebody unguarded.',
          '![Dwight Crow & crew after our fourth session](/images/poseidon/dwight-crew.jpg)',
          'Being authentic carries a level of asymmetry. Going first is expensive but serves as an invitation for others to do the same. Throughout the fellowship I reinvented myself. I decided to open up and let everyone know about the story I was writing for myself.',
          'I was afraid of being pitied. The response I got instead was, "what is the next venture?" That alone was what I needed to hear and enough to kickstart something in me. The cost of going first is priced almost entirely by your own imagination and in a sea of information, the more personal yours is, the less it resembles anyone else’s.',
        ],
      },
      {
        heading: '10. Give early',
        paragraphs: [
          'You don’t wait until you succeed to give. You succeed by giving.',
          'Being in debt, I can’t invest, hire, or fund anything. What I can do is notice someone, thank them, and tell them what their advice has actually produced. The threshold to give is far lower than people assume. It does not take extravagance, it takes a message, which is exactly why it belongs early in your career. I know what it does on the other end because at the lowest point of my life, someone gave back and changed the direction I was headed.',
          'When I received a scholarship out of high school I wrote to the person who had selected me six months later to say thank you. Last year we had lunch where he told me that I was the first student ever who had done that. I thought of the note as an ordinary courtesy. It cost me twenty minutes and he was still carrying it years later.',
          '![Shawn & Liz with some special gifts from the fellows](/images/poseidon/shawn-liz-gifts.jpg)',
          'The reason giving back feels impossible as an early grad is that everyone pictures giving upward. I have nothing to hand DJ Patil. But I am two years ahead of somebody who does not know this fellowship exists.',
          'The fellows have taken on an initiative of our own. I call it The Poseidon Post, one page from each founding fellow, passed down to every cohort that comes after us. The goal is to hand each new Poseidon Fellow a document of what we wish we would’ve known before our first session. It costs nothing but the time to write it, and none of us will be in the room when it gets read.',
        ],
      },
      {
        heading: 'Where this leaves me',
        paragraphs: [
          'I said earlier that this was the third personal inflection. The application was a Hail Mary written on a hiking trip through Sequoia National Park. I expected nothing from it and it became the reason I am writing this.',
          'The fellowship gave me a different set of defaults. It got me to look at all the pieces of myself that had fallen, gather them up, and go after the next thing.',
          '> Everything around you that you call life was made up by people no smarter than you.\n— Steve Jobs',
          'Where I am headed is into early stage startups. I am actively looking to join an ambitious team, bringing what deep failure taught me alongside the lessons I have accumulated this past spring. I am also building something of my own, a private closed-door venture summit that brings together the highest caliber founders with the necessary capital formation across San Diego. It serves to fill a gap I clearly see.',
          'The one thing I am doing immediately is the least obvious. I am slowing down. I have been running on a timeline somebody else set and it has cost me more presence than progress. I am spending more time on the things that actually matter: staying authentic, leaning not on my own understanding, and rejoicing through the tribulations rather than waiting for them to end.',
          'Being present is the most ambitious thing you can do, because it is a pursuit that never ends.',
          '> We win when we pick up everyone around us.\n— DJ Patil',
          'A special thanks to Shawn Xu & Elizabeth Lyons for making this fellowship possible. Thank you Michael Retchin, DJ Patil, Dwight Crow, Jimmy Douglas, and Tess Hatch for your advice and wise words! To the 11 fellows that bounced ideas around with me, much to come!',
        ],
      },
    ],
  },

  /* ARCHIVED — pulled from the Writing index in writing.ts while it is
     revised. Text kept here so restoring it is a one-line change. */
  'building-for-the-wrong-audience': {
    title: 'Building for the Wrong Audience',
    sections: [
      {
        paragraphs: [
          'I’ll start with a number. $500,000. At 20 years old, I was watching that number on a screen, and I genuinely believed that when it hit a million, something in my life would finally click into place. I couldn’t tell you exactly what that something was. I just knew, with total certainty, that the number would deliver it.',
          'It didn’t. And before I could even articulate what I thought it was going to give me, the number started going the other direction, and it didn’t stop for months. Not in a dramatic, single-moment crash that makes for a clean story. It was slower than that, and somehow that made it worse, because every single day I woke up with another opportunity to stop, to be honest with myself, to tell someone what was happening, and every single day I chose not to. I chose the idea I had already committed to in my head over the reality that was unfolding in front of me. I kept building on a foundation I already knew was cracking because I couldn’t separate the outcome from who I believed I was.',
          'I’m 21 years old, and I am writing this having lost money I owe to people I love, having spent the better part of a year waking up in the middle of the night unable to breathe, and having learned something that I don’t think I could have read in a book or heard in a lecture or absorbed from someone else’s story. I learned that I had spent my entire life, from the time I was a teenager, building things for the wrong audience.',
          'Let me explain what I mean by that.',
          'When I was in high school, I was obsessed with my grades. And I don’t mean the kind of obsession that comes from loving learning or being curious about the world, though I do think that curiosity was always there underneath it. I mean the kind of obsession that comes from needing something from someone who doesn’t know how to give it to you. My father is not an emotionally present person. He never has been. And somewhere along the way, without ever making a conscious decision about it, I concluded that if I could just perform well enough, achieve visibly enough, bring home something undeniable enough, that he would finally reflect back to me what I needed to see. I became valedictorian of my high school class. I remember looking at the ceiling of my room and feeling almost nothing, because the one person whose acknowledgement I was actually after didn’t know how to give it, and didn’t even fully understand that I needed it.',
          'So I moved the goalpost. When one achievement doesn’t deliver what you hoped it would, the brain doesn’t conclude that achievement isn’t the answer. It concludes that you just haven’t achieved enough yet. So I got to college and scaled up my detailing business that I started in high school, and I want to be honest about why, because the real reason is particularly embarrassing which is exactly why it’s worth saying out loud. A girl broke my heart, and my response, in the way that only an 18 year old boy can reason, was to build something impressive enough that she would have to recognize what she’d walked away from. Unfortunately, I was not in a Disney fairytale and she didn’t come back. So the only rational plan was to move the goalpost again.',
          'This pattern has been a common occurrence among the young ambitious friends I regularly speak to in university. In a world encouraging consumption and endless competition we are conditioned to run hard towards excellence without ever stopping to ask who exactly we are running for.',
          'By the time I got to college, I had developed what I called a script. A four year written plan, with specific financial milestones, experiences, positions I needed to hold and relationships I needed to build. I treated it less like a plan and more like a contract I had signed with some future version of myself. The script detailed how I would graduate with $100,000. That was the initial number I had decided to represent proof that I was serious, that I was different, that I wasn’t just another college kid talking about wanting to do something meaningful with his life.',
          'I hit $100,000 faster than I expected, and instead of feeling the satisfaction I had promised myself I would feel, I was consistent with what I had always done. I moved the goalpost and the script got revised. Soon it was $500,000. And then I hit that too, and I remember the specific moment I looked at my portfolio account and thought, a million dollars, that’s the number, that’s when it becomes real, that’s when I’ll know. I was not being reckless in the way that looks obvious from the outside. I had built a thesis, I had watched it work, I had convinced myself through the evidence of my own recent success that I understood something other people didn’t, and that conviction felt indistinguishable from clarity.',
          'This is the part of the story that I’ve had to think about the hardest, because it would be easy to tell you that I was young and naive and didn’t understand risk, and leave it there. But that’s not quite honest enough. The truth is that I understood risk in the abstract. What I didn’t understand was the way my own psychology was operating underneath every decision I was making. I wasn’t managing a portfolio but an identity. The account wasn’t a financial instrument to me, it was a scoreboard, and the score was how I was measuring whether I was becoming the person I had decided I needed to be. An instrument to justify my existence in the world. And when the numbers started going in the opposite direction, I couldn’t cut the position the way any rational framework would have told me to, because cutting the position meant admitting something about myself that I wasn’t ready to admit.',
          'So I held. And I added. And I watched it bleed for months.',
          'I want to try to describe this period of time, as I think this is the part that gets left out of most stories regarding failure, the part that happens between when things start going wrong and when you finally tell someone. I was waking up at two, three in the morning, heart pounding, this specific dread sitting on my chest that I couldn’t fully articulate even to myself. I was going to class and sitting across from my friends at dinner and walking through my campus and carrying this weight that nobody around me could see, and I was choosing that, every single day, because telling someone felt like the one thing that would make it irreversibly real. As long as it was private, there was still a version of the story where it turned around and nobody ever had to know it happened. I was protecting the narrative more than I was protecting myself.',
          'The money I lost wasn’t only mine. That’s the part that still sits heaviest. I had borrowed from some of my closest friends, people who trusted me not because I had shown them a prospectus or laid out a risk framework, but because they knew me and believed in me as a person. And I was carrying that privately too, this specific shame of knowing that my failure had edges that extended into people I loved, while simultaneously telling myself I would fix it before it ever had to become a conversation. I would earn it back and repay it quietly and the story would end cleanly that I would be the only one who ever knew how close to the edge it had gotten.',
          'That is not what happened.',
          'What happened instead was a slow accumulation of months until the weight became impossible to carry alone, and I started, cautiously and imperfectly, letting people in. First one person, then another, then the community I had found through a fellowship program that was teaching me what it actually meant to build something, not just the mechanics of it but the human architecture underneath it, the self-awareness and the relationships, the honest reckoning with your own motivations that determine whether what you build lasts or collapses under its own contradictions.',
          'And in one of those early sessions, Shawn Xu, who leads the program, told us about Lowercarbon Capital, the firm he is currently at, founded by Chris and Crystal Sacca. During the dot-com era Chris took out his student loans and ran them up to 12 million dollars on aggressive margin before losing it all and ending up 4 million dollars in debt. And then, eventually talking his way into Google and living frugally, he would go on to become one of the most recognized venture investors of his generation. I remember sitting in that room and feeling something shift in my chest, not because the story made my situation okay, it didn’t, the debt was still real and the conversations I needed to have were still ahead of me, but because for the first time I saw my own arc reflected in someone else’s and understood that the crash was not the end of the story unless I decided it was.',
          'But here is what I’ve spent the most time thinking about since then, and this is really the center of what I want to write about. The lesson from that period of my life is not simply that I took too much risk, or that I should have had better position sizing, or that I was too young and too confident and needed to be humbled. Those things are all true, but they’re the surface layer. The deeper lesson is that I had built an entire operating system for my life around external validation, and I had never once stopped to examine it, because it kept producing results that looked like success from the outside. Valedictorian. Profitable business. Growing account. Impressive numbers. I was so good at achieving things that I never had to confront the question of whether I was achieving them for reasons that were actually mine.',
          'And that question, it turns out, is the most important one.',
          'If you are reading this, I want to ask you something, and I want you to actually sit with it rather than answering it immediately in your head the way we tend to do when someone asks us a question we already think we know the answer to.',
          'Who are you building for?',
          'Not the answer you would give in a job interview, or on a first date, or at a dinner where you want to seem like the kind of person who has their priorities straight. The real answer. The one that lives underneath the goals you’ve written down and the milestones you’re chasing and the version of your future self you’ve constructed in your mind. When you imagine achieving the thing you’re working toward right now, who is in the room when it happens? Whose face do you see? Whose voice do you hear telling you that you finally did it?',
          'Because I think for a lot of us, if we’re honest, the answer to that question is someone who isn’t going to give us what we’re looking for even when we get there. A parent who shows love through criticism rather than warmth. A person who left. A version of ourselves from five years ago that we’re still trying to prove wrong. A room full of people from our hometown who doubted us. We are remarkably good at constructing elaborate futures oriented around audiences who will never fully satisfy us, and we are remarkably bad at noticing that we’re doing it, because the ambition feels so clean and so forward-facing that it doesn’t occur to us to look at what’s underneath it.',
          'I want to be clear that ambition is far from the problem. There’s a version of this message that becomes an excuse for smallness, a philosophical justification for not going after the things that scare you, and that is not what I’m saying. I am someone who still wakes up every morning oriented toward something large and difficult and uncertain. There is a meaningful difference between ambition that comes from genuine desire, from real curiosity about what you’re capable of and what you can contribute to the world, and ambition that comes from a wound you’re trying to close through achievement. Both can produce results. But only one of them produces results that you can actually feel.',
          'The version of me that was watching that account climb toward a million dollars was not experiencing joy. Looking back on it now, I can see that clearly, but I couldn’t see it then because I was so focused on the destination that I had completely lost contact with my own interior experience along the way. I was perpetually living in the moment when the number would finally be high enough, when the achievement would finally be sufficient, when I would finally be able to exhale and feel what I had been working toward. And that moment, I now understand, was never going to come. Not because success is an illusion, but because I had oriented my entire pursuit around a feeling that no external outcome was ever going to be able to deliver.',
          'What changed for me, and I want to be careful here because I don’t want to make this sound tidier than it actually was, was not a single moment of clarity. It was a slow accumulation of honesty. Telling one person the truth about what had happened. Then another. Sitting in rooms with people who were asking harder questions than I had been willing to ask myself. Starting to write, not for an audience, just for the purpose of finding out what I actually thought when I removed the performance of thinking from the equation. And gradually, imperfectly, I began to develop a relationship with my own motivations that was based on something other than what they were producing.',
          'I started asking myself, before I committed to something, not just whether it was impressive or strategic or financially sensible, but whether I actually wanted it. Whether the version of my life that included it felt more like mine or more like an answer to someone else’s question about who I should be. That distinction, which sounds simple when I say it out loud, turned out to be one of the hardest things I had ever tried to practice, because I had spent so many years optimizing for external legibility that I had genuinely lost touch with my own preferences underneath it all.',
          'Through all of it, I am still working on this. I want to be honest about that too, because these kinds of conversations become less useful than they could be when the person giving them has packaged their struggle into something too clean, too resolved, too much like a lesson that has already been fully learned. I am 21 years old and I still owe money to people I love and I still have days where the anxiety sits heavy and the old patterns pull at me and the goalpost starts moving again before I’ve even noticed it’s happening. This work is ongoing. What’s different is that I now know the work exists and I have people around me who are honest enough to tell me when I’m building for the wrong audience.',
          'That community turned out to be the thing I had been looking for all along. Not the number on the screen. Not the title or the validation or the proof of worth I had been trying to manufacture through achievement. Just people who knew the real version of the story and stayed anyway. People who asked the harder questions because they cared about the answer. That is what I was actually hungry for from the beginning, and it was never going to be delivered by any goalpost I was chasing. You cannot achieve your way into genuine connection. You can only get there by being honest enough to let people see what’s actually happening.',
          'So here is what I want to leave you with, and I want to say it as plainly as possible, not wrapped in something more eloquent.',
          'Examine who you are building for. Not once, not in a journal entry after a setback, but consistently, as a practice, as the kind of ongoing honest conversation with yourself that most of us avoid because it’s uncomfortable and it doesn’t produce anything you can put on a resume. Ask yourself whether the future you are working toward is one you genuinely want or one you have constructed to satisfy an audience that was never going to give you what you needed in the first place. If the answer is the latter, which for most of us it is, don’t use that as a reason to stop building. Use it as a reason to rebuild the foundation.',
          'One of the most important things I’ve learned at 21, through the consequences of mistakes, losses that still keep me up some nights, debts I’m still working to repay, is that if you can build something extraordinary on a foundation of someone else’s approval, imagine what is possible once you show up for yours.',
          'Lead with love, gravitate towards joy, and trust God.',
        ],
      },
    ],
  },

  /* ARCHIVED 2026-09-10 — note file moved to content/notes-archive/ while
     Fernando revises it. Text kept here; restoring means moving the .md back. */
  'social-death': {
    title: 'Social death',
    sections: [
      {
        paragraphs: [
          'For most of my life I have been going through the motions without noticing that I was, because the motions were the whole world and there was nothing to measure them against. School taught me to live by a checklist, and I was good at it, and the checklist never once finished. There was always the next thing to accomplish, the next place I needed to be, a next threshold I had to clear before I would finally be allowed to feel that my existence was justified. I moved through years of my life this way, doing everything that was asked and never stopping to ask why I was doing it or who I was doing it for. It did not feel like living, and the strangest part was that from the outside nothing looked wrong, because I was accomplishing exactly what I was supposed to accomplish, and no one, least of all me, thought to check whether the person doing all of it was actually there.',
          'This is what I have come to call social death, and it is not the absence of people or the absence of achievement, it is the condition of being alive without ever being witnessed, including by yourself. You can be surrounded, accounted for, present in every metric and every group chat, and still be nowhere. Presence is not the same as being felt, and a life spent completing a list someone else wrote is one in which the person living it slowly disappears. I see it everywhere on my campus, in students who are pushing harder than any generation before them and questioning it less, running a race whose finish line keeps moving, and I recognize it instantly because I was running it too. This never ending race to justify their existence in the world.',
          'I saw it most clearly on my own phone. At one point I had every app the culture handed me, TikTok and Instagram and Twitter and the rest, and I need to be honest that I did not download them because I loved them or chose them, I downloaded them because they were so completely woven into the life of everyone my age that not having them felt like not existing, and so I went along, the way I had gone along with everything else. The more I used them the more plainly addicting they revealed themselves to be, a design now alleged across a wave of lawsuits and backed by the companies’ own internal research. The more I fed them the more I felt this heavy, ambient unfulfillment, the specific weight of doing a great many things while living a life that was not actually mine. So I deleted all of it, and I am on the edge now of trading the smartphone for a flip phone, because once you have felt the difference you cannot unfeel it. What I found on the other side was not boredom. It was the return of a self I had outsourced without realizing I had signed it away.',
          'And when I look up from my own story my generation is describing the same thing in numbers. Three in five young adults say their lives lack meaning or purpose. Half say that not knowing what to do with their life is damaging their mental health. More than seven hundred thousand people take their own lives every year, one roughly every forty-five seconds, and among Americans between ages ten and twenty-four the suicide rate rose by about sixty-two percent from 2007 to 2021. Almost exactly the same timeline as the machine we all agreed to carry. Depression among adolescents climbed by more than half in the decade before the pandemic, and close to a third of young people will meet the criteria for an anxiety disorder at some point in their lives. We are the most connected, the most comfortable, and somehow the most lost generation in human history, and I do not think those three facts are unrelated. I think the comfort and the connection are how we got lost.',
          'Here is the mechanism as I have come to understand it, from the inside. A civilization built to consume needs your attention more than it needs your wellbeing, and so it engineers a stream of distraction so constant and so frictionless that you are never left alone long enough to actually feel anything. And feeling is not this luxury sitting on top of your life, it is the instrument that tells you where to go. Your sense of direction comes from noticing what genuinely moves you. Your happiness comes from being present enough to register it. Your sense of belonging comes from being felt by another person and feeling them back. Mass distraction interrupts all three at the source, because a person who is endlessly consuming is a person who is never quiet enough to feel, and a person who cannot feel loses the only compass that was ever going to point them toward direction, toward happiness, toward each other. The apps did not just waste our time. They robbed us of the faculty that a meaningful life is built out of, and then handed us a scoreboard to chase in its place.',
          'I have come to believe the phone did not create this so much as move into a space that was already empty. Dostoevsky put the stakes as plainly as anyone ever has, that the one essential condition of human existence is that man should always be able to bow down before something infinitely great, and that if men are deprived of the infinitely great they will not go on living and will die of despair. I believe that deprivation happened already. Community had been fragmenting for a long time, religion had been thinning out, the shared rituals that once placed a person inside something larger had already eroded, and into that empty room the device arrived and made itself indispensable, not by kicking down a door but by finding one left open. Aquinas saw the mechanism seven centuries early, when he wrote that man cannot live without joy, and that when he is deprived of true spiritual joys it is necessary that he become addicted to carnal pleasures. The apps did not invent our emptiness. They colonized it, and then sold us a thin joy to sit in its place.',
          'What makes the whole thing so hard to see clearly is exactly what makes it profitable, that the harm is spread thin while the benefit is gathered tightly. This has been a historical pattern. Cigarettes killed millions for the better part of a century before anything structural moved, because each death read as one family’s private grief while each dividend read as one company’s ordinary quarter. The same arithmetic holds with leaded gasoline and with opioids, the damage distributed across so many people that every one of them experiences it as a personal failing while the profit concentrates among a few who can afford the lawyers and the lobbyists and the story everyone eventually accepts. Depression arrives feeling like your particular problem. Anxiety arrives feeling like your particular weakness. Suicide is mourned one person at a time, and the aggregation, the fact that the same thing is happening to a whole generation through the same machinery, never assembles into a picture, because we are each suffering alone, and alone is exactly the condition under which suffering cannot be added up. I do not think that is an accident. Atomization is not a side effect of the system, it is one of the things the system is for, because alone you blame yourself, and only together would you think to blame the thing.',
          'The deepest part of the trap is the belief the whole machine runs on, that fulfillment is the fruit of a finished checklist, that once you reach the next level, earn the next label, become the doctor or clear the next threshold, you will finally receive the peace you keep imagining. It is a lie, and it is the specific lie that kept me going through the motions for years. Peace is not the reward for healing, it is the condition that allows healing to occur, and the moment you tie yourself to a label you accept the mental enslavement the label brings, because labels are conceptual prisons, and the good part is never actually around the corner. The grass is not greener on the other side, it is green where you water it. Being ready is a choice, not a prize handed out after enough tasks are complete. There is nothing wrong with reaching for the next thing, it is part of becoming who you can become, but the same reach that builds you can rot into a bottomless need for approval and a goalpost that retreats every time you near it, and a society drifting toward mass distraction has quietly made that rot the default.',
          'The way out is quieter than people expect, because it does not begin with an argument and it does not begin at the top. It begins when a person goes genuinely offline with themselves, questions the conditioning they never chose, and stops performing the life that was assigned to them. The strange thing is that this private act reads to everyone else as authenticity, and authenticity turns out to be an invitation. When you are finally, actually yourself, you give the people around you permission to ask whether they are being themselves, and one by one they can begin to set the mask down too. The apps are built to prevent exactly this, because the feed is a gallery of everyone’s highlight reel, a hall of curated masks in which no one ever encounters another person as they truly are, and a world where no one is authentically themselves is a world where no one is ever really seen. It does a quiet disservice to everyone, because we never get to witness each other in full, and we never get to find out who we actually are.',
          'But the ending is not written, because the one thing that reverses this is a small group of people so visibly alive, so obviously more present and more connected than the atomized life around them, that others are drawn toward it almost before they decide to be. Margaret Mead put it best: “Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it’s the only thing that ever has.” Social death is not undone by winning the argument against the machine. It is undone not by reasoning your way free but by putting the phone down, coming back to the self I had outsourced, and finding a few people warm enough to walk toward. The only real work in front of any of us is to become that warmth for someone else, and then to refuse to let it stay small.',
        ],
      },
    ],
    sourceNote:
      'Figures: Harvard Graduate School of Education (meaning and purpose in young adults); World Health Organization (global suicide); CDC / National Center for Health Statistics (US youth suicide, 2007–2021); Pew Research Center (adolescent depression). Quotations from Fyodor Dostoevsky (Demons), Thomas Aquinas, and Margaret Mead.',
  },

  /* ARCHIVED 2026-09-10 — note file moved to content/notes-archive/ while
     Fernando revises it. Text kept here; restoring means moving the .md back. */
  hovering: {
    title: 'Hovering',
    subtitle:
      'A reflection on romantic love in a world engineered for infinite options and against choosing.',
    sections: [
      {
        paragraphs: [
          'Choosing one person reveals beauty.',
          'It shows up first in their faults and again in the arrangement itself. Two become one and all of their problems become yours.',
          'The tools we built to find love are engineered to prevent this. Dating apps promise volume and call it connection. Their feeds produce infinite options and the abundance feels like freedom. The whole mechanic runs on faults. You see one so you swipe and another person arrives. What this technology is best at removing is also what everyone is looking for.',
          'We swipe under the impression that we are searching, when the searching has become the thing itself. It is a hovering above commitment that we call keeping our options open.',
          'A culture built on consumption will eventually appraise people the way it does everything else. People end up as packages to be compared, valued, and traded up. Even sex, which used to have a language of union, has shed that pretense. It is transactional by design and casual by consensus. We speak of cracking instead of making love.',
          'When I deleted all my social media apps I thought I would miss the people. I kept reaching for my phone, and what I missed was the reassurance that connection was possible with someone I had yet to meet. This is what the feed and dating apps sell.',
          'The absence aches badly enough that a fleeting version of connection feels viable. I used to take the fleeting version and it would quiet the hunger without ever touching it. What is missing is the willingness to be introspective enough to know what we actually want, and then brave enough to want it in front of another person.',
        ],
      },
    ],
  },
}
