import type { EssaySection } from './aboutEssay'

/* On-site long-form pieces, keyed by slug. A note in the Writing section
   shows a blurb and links here; the full text opens in the ReadingOverlay
   (same full-screen reader as the About essay). */
export type Essay = {
  title: string
  sections: EssaySection[]
  sourceNote?: string
}

export const essaysBySlug: Record<string, Essay> = {
  'building-for-the-wrong-audience': {
    title: 'Building for the Wrong Audience',
    sections: [
      {
        paragraphs: [
          'I’ll start with a number. $500,000. At 20 years old, I was watching that number on a screen, and I genuinely believed that when it hit a million, something in my life would finally click into place. I couldn’t tell you exactly what that something was. I just knew, with total certainty, that the number would deliver it.',
          'It didn’t. And before I could even articulate what I thought it was going to give me, the number started going the other direction, and it didn’t stop for months. Not in a dramatic, single-moment crash that makes for a clean story. It was slower than that, and somehow that made it worse, because every single day I woke up with another opportunity to stop, to be honest with myself, to tell someone what was happening, and every single day I chose not to. I chose the idea I had already committed to in my head over the reality that was unfolding in front of me. I kept building on a foundation I already knew was cracking because I couldn’t separate the outcome from who I believed I was.',
          'I’m 21 years old, and I am writing this having lost money I owe to people I love, having spent the better part of a year waking up in the middle of the night unable to breathe, and having learned something that I don’t think I could have read in a book or heard in a lecture or absorbed from someone else’s story. I learned that I had spent my entire life, from the time I was a teenager, building things for the wrong audience.',
          'Let me explain what I mean by that.',
          'When I was in high school, I was obsessed with my grades. And I don’t mean the kind of obsession that comes from loving learning or being curious about the world, though I do think that curiosity was always there underneath it. I mean the kind of obsession that comes from needing something from someone who doesn’t know how to give it to you. My father is not an emotionally present person. He never has been. And somewhere along the way, without ever making a conscious decision about it, I concluded that if I could just perform well enough, achieve visibly enough, bring home something undeniable enough, that he would finally reflect back to me what I needed to see. I became valedictorian of my high school class. I remember looking at the ceiling of my room and feeling almost nothing, because the one person whose acknowledgement I was actually after didn’t know how to give it, and didn’t even fully understand that I needed it.',
          'So I moved the goalpost. When one achievement doesn’t deliver what you hoped it would, the brain doesn’t conclude that achievement isn’t the answer. It concludes that you just haven’t achieved enough yet. So I got to college and scaled up my detailing business that I started in high school, and I want to be honest about why, because the real reason is particularly embarrassing which is exactly why it’s worth saying out loud. A girl broke my heart, and my response, in the way that only an 18 year old boy can reason, was to build something impressive enough that she would have to recognize what she’d walked away from. Unfortunately, I was not in a Disney fairytale and she didn’t come back. So the only rational plan was to move the goalpost again.',
          'This pattern has been a common occurrence among the young ambitious friends I regularly speak to in university. In a world encouraging consumption and endless competition we are conditioned to run hard towards excellence without ever stopping to ask who exactly we are running for.',
          'By the time I got to college, I had developed what I called a script. A four year written plan, with specific financial milestones, experiences, positions I needed to hold and relationships I needed to build. I treated it less like a plan and more like a contract I had signed with some future version of myself. The script detailed how I would graduate with $100,000. That was the initial number I had decided to represent proof that I was serious, that I was different, that I wasn’t just another college kid talking about wanting to do something meaningful with his life.',
          'I hit $100,000 faster than I expected, and instead of feeling the satisfaction I had promised myself I would feel, I was consistent with what I had always done. I moved the goalpost and the script got revised. Soon it was $500,000. And then I hit that too, and I remember the specific moment I looked at my portfolio account and thought, a million dollars, that’s the number, that’s when it becomes real, that’s when I’ll know. I was not being reckless in the way that looks obvious from the outside. I had built a thesis, I had watched it work, I had convinced myself through the evidence of my own recent success that I understood something other people didn’t, and that conviction felt indistinguishable from clarity.',
          'This is the part of the story that I’ve had to think about the hardest, because it would be easy to tell you that I was young and naive and didn’t understand risk, and leave it there. But that’s not quite honest enough. The truth is that I understood risk in the abstract. What I didn’t understand was the way my own psychology was operating underneath every decision I was making. I wasn’t managing a portfolio but an identity. The account wasn’t a financial instrument to me, it was a scoreboard, and the score was how I was measuring whether I was becoming the person I had decided I needed to be. An instrument to justify my existence in the world. And when the numbers started going in the opposite direction, I couldn’t cut the position the way any rational framework would have told me to, because cutting the position meant admitting something about myself that I wasn’t ready to admit.',
          'So I held. And I added. And I watched it bleed for months.',
          'I want to try to describe this period of time, as I think this is the part that gets left out of most stories regarding failure, the part that happens between when things start going wrong and when you finally tell someone. I was waking up at two, three in the morning, heart pounding, this specific dread sitting on my chest that I couldn’t fully articulate even to myself. I was going to class and sitting across from my friends at dinner and walking through my campus and carrying this weight that nobody around me could see, and I was choosing that, every single day, because telling someone felt like the one thing that would make it irreversibly real. As long as it was private, there was still a version of the story where it turned around and nobody ever had to know it happened. I was protecting the narrative more than I was protecting myself.',
          'The money I lost wasn’t only mine. That’s the part that still sits heaviest. I had borrowed from some of my closest friends, people who trusted me not because I had shown them a prospectus or laid out a risk framework, but because they knew me and believed in me as a person. And I was carrying that privately too, this specific shame of knowing that my failure had edges that extended into people I loved, while simultaneously telling myself I would fix it before it ever had to become a conversation. I would earn it back and repay it quietly and the story would end cleanly that I would be the only one who ever knew how close to the edge it had gotten.',
          'That is not what happened.',
          'What happened instead was a slow accumulation of months until the weight became impossible to carry alone, and I started, cautiously and imperfectly, letting people in. First one person, then another, then the community I had found through a fellowship program that was teaching me what it actually meant to build something, not just the mechanics of it but the human architecture underneath it, the self-awareness and the relationships, the honest reckoning with your own motivations that determine whether what you build lasts or collapses under its own contradictions.',
          'And in one of those early sessions, Shawn Xu, who leads the program, told us about Lowercarbon Capital, the firm he is currently at, founded by Chris and Crystal Sacca. During the dot-com era Chris took out his student loans and ran them up to 12 million dollars on aggressive margin before losing it all and ending up 4 million dollars in debt. And then, eventually talking his way into Google and living frugally, he would go on to become one of the most recognized venture investors of his generation. I remember sitting in that room and feeling something shift in my chest, not because the story made my situation okay, it didn’t, the debt was still real and the conversations I needed to have were still ahead of me, but because for the first time I saw my own arc reflected in someone else’s and understood that the crash was not the end of the story unless I decided it was.',
          'But here is what I’ve spent the most time thinking about since then, and this is really the center of what I want to write about. The lesson from that period of my life is not simply that I took too much risk, or that I should have had better position sizing, or that I was too young and too confident and needed to be humbled. Those things are all true, but they’re the surface layer. The deeper lesson is that I had built an entire operating system for my life around external validation, and I had never once stopped to examine it, because it kept producing results that looked like success from the outside. Valedictorian. Profitable business. Growing account. Impressive numbers. I was so good at achieving things that I never had to confront the question of whether I was achieving them for reasons that were actually mine.',
          'And that question, it turns out, is the most important one.',
          'If you are reading this, I want to ask you something, and I want you to actually sit with it rather than answering it immediately in your head the way we tend to do when someone asks us a question we already think we know the answer to.',
          'Who are you building for?',
          'Not the answer you would give in a job interview, or on a first date, or at a dinner where you want to seem like the kind of person who has their priorities straight. The real answer. The one that lives underneath the goals you’ve written down and the milestones you’re chasing and the version of your future self you’ve constructed in your mind. When you imagine achieving the thing you’re working toward right now, who is in the room when it happens? Whose face do you see? Whose voice do you hear telling you that you finally did it?',
          'Because I think for a lot of us, if we’re honest, the answer to that question is someone who isn’t going to give us what we’re looking for even when we get there. A parent who shows love through criticism rather than warmth. A person who left. A version of ourselves from five years ago that we’re still trying to prove wrong. A room full of people from our hometown who doubted us. We are remarkably good at constructing elaborate futures oriented around audiences who will never fully satisfy us, and we are remarkably bad at noticing that we’re doing it, because the ambition feels so clean and so forward-facing that it doesn’t occur to us to look at what’s underneath it.',
          'I want to be clear that ambition is far from the problem. There’s a version of this message that becomes an excuse for smallness, a philosophical justification for not going after the things that scare you, and that is not what I’m saying. I am someone who still wakes up every morning oriented toward something large and difficult and uncertain. There is a meaningful difference between ambition that comes from genuine desire, from real curiosity about what you’re capable of and what you can contribute to the world, and ambition that comes from a wound you’re trying to close through achievement. Both can produce results. But only one of them produces results that you can actually feel.',
          'The version of me that was watching that account climb toward a million dollars was not experiencing joy. Looking back on it now, I can see that clearly, but I couldn’t see it then because I was so focused on the destination that I had completely lost contact with my own interior experience along the way. I was perpetually living in the moment when the number would finally be high enough, when the achievement would finally be sufficient, when I would finally be able to exhale and feel what I had been working toward. And that moment, I now understand, was never going to come. Not because success is an illusion, but because I had oriented my entire pursuit around a feeling that no external outcome was ever going to be able to deliver.',
          'What changed for me, and I want to be careful here because I don’t want to make this sound tidier than it actually was, was not a single moment of clarity. It was a slow accumulation of honesty. Telling one person the truth about what had happened. Then another. Sitting in rooms with people who were asking harder questions than I had been willing to ask myself. Starting to write, not for an audience, just for the purpose of finding out what I actually thought when I removed the performance of thinking from the equation. And gradually, imperfectly, I began to develop a relationship with my own motivations that was based on something other than what they were producing.',
          'I started asking myself, before I committed to something, not just whether it was impressive or strategic or financially sensible, but whether I actually wanted it. Whether the version of my life that included it felt more like mine or more like an answer to someone else’s question about who I should be. That distinction, which sounds simple when I say it out loud, turned out to be one of the hardest things I had ever tried to practice, because I had spent so many years optimizing for external legibility that I had genuinely lost touch with my own preferences underneath it all.',
          'Through all of it, I am still working on this. I want to be honest about that too, because these kinds of conversations become less useful than they could be when the person giving them has packaged their struggle into something too clean, too resolved, too much like a lesson that has already been fully learned. I am 21 years old and I still owe money to people I love and I still have days where the anxiety sits heavy and the old patterns pull at me and the goalpost starts moving again before I’ve even noticed it’s happening. This work is ongoing. What’s different is that I now know the work exists and I have people around me who are honest enough to tell me when I’m building for the wrong audience.',
          'That community turned out to be the thing I had been looking for all along. Not the number on the screen. Not the title or the validation or the proof of worth I had been trying to manufacture through achievement. Just people who knew the real version of the story and stayed anyway. People who asked the harder questions because they cared about the answer. That is what I was actually hungry for from the beginning, and it was never going to be delivered by any goalpost I was chasing. You cannot achieve your way into genuine connection. You can only get there by being honest enough to let people see what’s actually happening.',
          'So here is what I want to leave you with, and I want to say it as plainly as possible, not wrapped in something more eloquent.',
          'Examine who you are building for. Not once, not in a journal entry after a setback, but consistently, as a practice, as the kind of ongoing honest conversation with yourself that most of us avoid because it’s uncomfortable and it doesn’t produce anything you can put on a resume. Ask yourself whether the future you are working toward is one you genuinely want or one you have constructed to satisfy an audience that was never going to give you what you needed in the first place. If the answer is the latter, which for most of us it is, don’t use that as a reason to stop building. Use it as a reason to rebuild the foundation.',
          'One of the most important things I’ve learned at 21, through the consequences of mistakes, losses that still keep me up some nights, debts I’m still working to repay, is that if you can build something extraordinary on a foundation of someone else’s approval, imagine what is possible once you show up for yours.',
          'Lead with love, gravitate towards joy, and trust God.',
        ],
      },
    ],
  },

  'social-death': {
    title: 'Social death',
    sections: [
      {
        paragraphs: [
          'For most of my life I have been going through the motions without noticing that I was, because the motions were the whole world and there was nothing to measure them against. School taught me to live by a checklist, and I was good at it, and the checklist never once finished. There was always the next thing to accomplish, the next place I needed to be, a next threshold I had to clear before I would finally be allowed to feel that my existence was justified. I moved through years of my life this way, doing everything that was asked and never stopping to ask why I was doing it or who I was doing it for. It did not feel like living, and the strangest part was that from the outside nothing looked wrong, because I was accomplishing exactly what I was supposed to accomplish, and no one, least of all me, thought to check whether the person doing all of it was actually there.',
          'This is what I have come to call social death, and it is not the absence of people or the absence of achievement, it is the condition of being alive without ever being witnessed, including by yourself. You can be surrounded, accounted for, present in every metric and every group chat, and still be nowhere. Presence is not the same as being felt, and a life spent completing a list someone else wrote is one in which the person living it slowly disappears. I see it everywhere on my campus, in students who are pushing harder than any generation before them and questioning it less, running a race whose finish line keeps moving, and I recognize it instantly because I was running it too. This never ending race to justify their existence in the world.',
          'I saw it most clearly on my own phone. At one point I had every app the culture handed me, TikTok and Instagram and Twitter and the rest, and I need to be honest that I did not download them because I loved them or chose them, I downloaded them because they were so completely woven into the life of everyone my age that not having them felt like not existing, and so I went along, the way I had gone along with everything else. The more I used them the more plainly addicting they revealed themselves to be, a design now alleged across a wave of lawsuits and backed by the companies’ own internal research. The more I fed them the more I felt this heavy, ambient unfulfillment, the specific weight of doing a great many things while living a life that was not actually mine. So I deleted all of it, and I am on the edge now of trading the smartphone for a flip phone, because once you have felt the difference you cannot unfeel it. What I found on the other side was not boredom. It was the return of a self I had outsourced without realizing I had signed it away.',
          'And when I look up from my own story my generation is describing the same thing in numbers. Three in five young adults say their lives lack meaning or purpose. Half say that not knowing what to do with their life is damaging their mental health. More than seven hundred thousand people take their own lives every year, one roughly every forty-five seconds, and among Americans between ages ten and twenty-four the suicide rate rose by about sixty-two percent from 2007 to 2021. Almost exactly the same timeline as the machine we all agreed to carry. Depression among adolescents climbed by more than half in the decade before the pandemic, and close to a third of young people will meet the criteria for an anxiety disorder at some point in their lives. We are the most connected, the most comfortable, and somehow the most lost generation in human history, and I do not think those three facts are unrelated. I think the comfort and the connection are how we got lost.',
          'Here is the mechanism as I have come to understand it, from the inside. A civilization built to consume needs your attention more than it needs your wellbeing, and so it engineers a stream of distraction so constant and so frictionless that you are never left alone long enough to actually feel anything. And feeling is not this luxury sitting on top of your life, it is the instrument that tells you where to go. Your sense of direction comes from noticing what genuinely moves you. Your happiness comes from being present enough to register it. Your sense of belonging comes from being felt by another person and feeling them back. Mass distraction interrupts all three at the source, because a person who is endlessly consuming is a person who is never quiet enough to feel, and a person who cannot feel loses the only compass that was ever going to point them toward direction, toward happiness, toward each other. The apps did not just waste our time. They robbed us of the faculty that a meaningful life is built out of, and then handed us a scoreboard to chase in its place.',
          'I have come to believe the phone did not create this so much as move into a space that was already empty. Dostoevsky put the stakes as plainly as anyone ever has, that the one essential condition of human existence is that man should always be able to bow down before something infinitely great, and that if men are deprived of the infinitely great they will not go on living and will die of despair. I believe that deprivation happened already. Community had been fragmenting for a long time, religion had been thinning out, the shared rituals that once placed a person inside something larger had already eroded, and into that empty room the device arrived and made itself indispensable, not by kicking down a door but by finding one left open. Aquinas saw the mechanism seven centuries early, when he wrote that man cannot live without joy, and that when he is deprived of true spiritual joys it is necessary that he become addicted to carnal pleasures. The apps did not invent our emptiness. They colonized it, and then sold us a thin joy to sit in its place.',
          'What makes the whole thing so hard to see clearly is exactly what makes it profitable, that the harm is spread thin while the benefit is gathered tightly. This has been a historical pattern. Cigarettes killed millions for the better part of a century before anything structural moved, because each death read as one family’s private grief while each dividend read as one company’s ordinary quarter. The same arithmetic holds with leaded gasoline and with opioids, the damage distributed across so many people that every one of them experiences it as a personal failing while the profit concentrates among a few who can afford the lawyers and the lobbyists and the story everyone eventually accepts. Depression arrives feeling like your particular problem. Anxiety arrives feeling like your particular weakness. Suicide is mourned one person at a time, and the aggregation, the fact that the same thing is happening to a whole generation through the same machinery, never assembles into a picture, because we are each suffering alone, and alone is exactly the condition under which suffering cannot be added up. I do not think that is an accident. Atomization is not a side effect of the system, it is one of the things the system is for, because alone you blame yourself, and only together would you think to blame the thing.',
          'The deepest part of the trap is the belief the whole machine runs on, that fulfillment is the fruit of a finished checklist, that once you reach the next level, earn the next label, become the doctor or clear the next threshold, you will finally receive the peace you keep imagining. It is a lie, and it is the specific lie that kept me going through the motions for years. Peace is not the reward for healing, it is the condition that allows healing to occur, and the moment you tie yourself to a label you accept the mental enslavement the label brings, because labels are conceptual prisons, and the good part is never actually around the corner. The grass is not greener on the other side, it is green where you water it. Being ready is a choice, not a prize handed out after enough tasks are complete. There is nothing wrong with reaching for the next thing, it is part of becoming who you can become, but the same reach that builds you can rot into a bottomless need for approval and a goalpost that retreats every time you near it, and a society drifting toward mass distraction has quietly made that rot the default.',
          'The way out is quieter than people expect, because it does not begin with an argument and it does not begin at the top. It begins when a person goes genuinely offline with themselves, questions the conditioning they never chose, and stops performing the life that was assigned to them. The strange thing is that this private act reads to everyone else as authenticity, and authenticity turns out to be an invitation. When you are finally, actually yourself, you give the people around you permission to ask whether they are being themselves, and one by one they can begin to set the mask down too. The apps are built to prevent exactly this, because the feed is a gallery of everyone’s highlight reel, a hall of curated masks in which no one ever encounters another person as they truly are, and a world where no one is authentically themselves is a world where no one is ever really seen. It does a quiet disservice to everyone, because we never get to witness each other in full, and we never get to find out who we actually are.',
          'But the ending is not written, because the one thing that reverses this is a small group of people so visibly alive, so obviously more present and more connected than the atomized life around them, that others are drawn toward it almost before they decide to be. Margaret Mead put it best: “Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it’s the only thing that ever has.” Social death is not undone by winning the argument against the machine. It is undone not by reasoning your way free but by putting the phone down, coming back to the self I had outsourced, and finding a few people warm enough to walk toward. The only real work in front of any of us is to become that warmth for someone else, and then to refuse to let it stay small.',
        ],
      },
    ],
    sourceNote:
      'Figures: Harvard Graduate School of Education (meaning and purpose in young adults); World Health Organization (global suicide); CDC / National Center for Health Statistics (US youth suicide, 2007–2021); Pew Research Center (adolescent depression). Quotations from Fyodor Dostoevsky (Demons), Thomas Aquinas, and Margaret Mead.',
  },

  'the-evacuation-of-love': {
    title: 'The evacuation of love',
    sections: [
      {
        paragraphs: [
          'Nowhere has the quiet hollowing of connection gone further than in the way people my age love, or in what we have started calling love in its place. We have let it thin until the word meant less than it used to, and now the thing that once carried the whole weight of union has been emptied so gradually that most people my age cannot remember it ever being heavier. We have not deconstructed love, we have quietly evacuated it.',
          'The clearest evidence is in the tools we built to find it. A dating app does not promise connection, it promises volume, and it offers the comfort of infinite options as a substitute for the one terrifying thing that love has always actually required, which is the singularity of choosing a person and closing the door on everyone else. Abundance feels like freedom, and for almost everything else it is, but choosing is the one act that abundance quietly destroys. A choice is only real to the degree that it costs the alternatives. A feed engineered to never run out has removed the cost and therefore removed the choice. We swipe under the impression that we are searching, when the searching has become the thing itself, this permanent hovering above commitment that we mistake for keeping our options open.',
          'This was beautifully orchestrated by Erich Fromm when he argued that we treat love as a feeling we fall into rather than an act we practice, and that a culture organized around consumption would inevitably start appraising people the way it appraises everything else, as packages to be compared, valued, and traded up. That is precisely where I believe we have landed. Sex, once burdened by the language of union, has shed even that pretense and become transactional by design and casual by consensus, we no longer speak of making love, we speak of cracking, and this semantic change is the whole confession.',
          'I believe we chose this not in an effort of wanting less but because genuine choosing is frightening, and the void where connection used to be aches badly enough that a fleeting version feels better than sitting in the absence, and so we fill it with the endless small desires and distractions that are always within reach. Yet those never touch the actual hunger, they only quiet it long enough to keep us from noticing it, which is exactly why the ache never resolves and the scrolling never stops. What is missing is not more options. It is the willingness to be introspective enough to know what we actually want, and then brave enough to want it in front of another person.',
          'I write this as someone inside it, as I have felt the pull of the infinite feed and mistaken the hovering for freedom. I have come to believe that real intimacy is the kind we are most afraid of, the kind that requires choosing one person and one life and letting all the other versions go. In a world built to keep us from ever landing, it may be the most radical thing we have left.',
        ],
      },
    ],
  },
}
