import type { EssaySection } from './aboutEssay'
import { thesisWriteup } from './thesisWriteup'

/* Long-form project write-ups, opened from the Projects wall. Same
   renderer as the Writing essays (ReadingOverlay), so a paragraph of
   "![caption](/path.jpg)" becomes a captioned figure and "> quote"
   becomes a pull quote. */
export type Writeup = {
  title: string
  subtitle?: string
  sections: EssaySection[]
}

export const writeupsBySlug: Record<string, Writeup> = {
  'investment-thesis': thesisWriteup,
  'danos-detailing': {
    title: 'Dano\u2019s Detailing',
    subtitle: 'Built on a mailroom flyer and other people\u2019s water.',
    sections: [
      {
        paragraphs: [
          'When I was seventeen, I spent my afternoons cooking pizza for $17 an hour at Mod Pizza. Whether I made fifty or five pizzas in an hour, I was still paid $17. After enough shifts, I thought to myself, there has to be a better way than exchanging my time for money.',
          'I quit in August of 2022 during my senior year of high school and started detailing cars in my hometown of Tracy, California. Over the next two years Dano’s Detailing went from a flyer on a mailroom bulletin board to a rotating crew of employees, a door to door sales team, and a catalog acquisition.',
          '![Freshly detailed Porsche 911 Carrera 4s.](/images/danos/porsche-911.jpg)',
          'The hardest part was getting the first person to say yes. Who was going to buy from a seventeen-year-old with no credibility? No luxury car owner was going to let me work on their car and potentially scratch it. Neither were dealerships or industry professionals. Everywhere I looked, my age was seen as a risk.',
          'I began searching where risk tolerance was the highest. Tracy is an agricultural town turned suburban commuter city. What I found was that it was filled with mothers who had no way to keep up with their car between doing groceries, dropping kids off at school, and overall chores. I found out that they mostly concentrated in Facebook groups. Facebook moms were glad to hire someone who would work around their busy schedule, arrive at their house, and deal with the headache of a messy car. Hiring a high schooler that was saving for college also gave them something a professional detailer never could. They were given the opportunity of helping a kid out.',
          'I began offering cheap or even free detailing to my friends and family. Low-stakes clients meant I could build up my portfolio and understand the timing, pricing, and difficulty that came with detailing cars.',
          '![One of my first ever interior detailing jobs.](/images/danos/first-interior.jpg)',
          'When I had enough practice, I made my first flyer and put it up on my neighborhood mailroom bulletin board. I wanted to gauge interest in my services and deliberately charged below market prices. This meant a full interior and exterior detail for $75 and a complete clay bar, wax, and seal for $150. I never intended to heavily undercharge market prices so as to not start a race to the bottom. I didn’t want price to be the reason anyone hired me.',
          'There was not much of a market to price against in 2022. Tracy had a handful of detailers and most were exclusively body shops. One did paint protection film, the other focused on ceramic coatings. Neither one would come to your driveway on a Saturday morning and clean out a minivan. Nobody was serving these people.',
          '![My first ever promo flyer. Looking back, this needs desperate improvement.](/images/danos/flyer.png)',
          'Eventually, my first client reached out after I posted in one of the Facebook groups. In the post, I attached my flyer and gave a quick pitch on what I was doing. My posts instantly became a hit sensation and I purposefully took on disgusting interiors that could give me dramatic before-and-after pictures. These pictures would end up becoming my greatest marketing tool.',
          'For every Facebook customer I served I would ask for a post in the group and a Google review. This created a flywheel of customer inbound and once my first review landed, I started getting requests for quotes. I kept leaning into the Facebook groups and cultivating a strong community presence in them. After enough completed jobs, my friend’s dad took notice. He offered to pay me to detail his Lotus Elise, and that became my first real credibility break.',
          '![The Lotus Elise that started it all.](/images/danos/lotus-elise.jpg)',
          'Clients began pouring in from all different channels mentioning they either saw my Facebook posts, word spread from their neighbor, or they recognized my business on Google. I even had clients who wanted me to start detailing their boats.',
          'The best client I had, found me through none of these. I was interviewing for a scholarship, and one of the panelists asked how I liked running my business. I mentioned how difficult it was and the drive that it created in me. It just so happened that his father owned a fleet of classic cars and his family would drive them through the Fourth of July parade every year. He needed someone to maintain them year round and this sparked a multi year long relationship between his family and I.',
          '![Receiving my scholarship and hearing “I still need you to come work on the cars.” A meaningful moment and turning point in the credibility of my business I won’t ever forget.](/images/danos/scholarship.jpg)',
          'Getting a client once was the easy part. The business ran on them calling again and telling their neighbor. For a mother hiring a teenager off Facebook, the worry was whether a stranger would show up when he said he would, be careful around her house, and not need chasing. And so I built the job around that.',
          'Before starting, I asked what specifically bothered them about the car and what needed extra attention. I sent an ETA, told them where I was, and said what I needed ready when I arrived early. If a stain was not coming out, I called them outside in the middle of the job and told them. I would walk them through the car once I finished and always start with the bad news. I pointed at the stain I could not lift and the scuff I had noticed before I pointed at anything that I was proud of. After I got paid, I would tell them to text me if they spotted anything at all so that I could come back the next day. I left every car with mints, a microfiber towel, my business card, and a bag of everything I found. All the coins and items that had gone missing underneath the seats.',
          'Volunteering the defects in my services was expensive in the moment, but served as a credible way to be believed about everything else. If I told my clients about the one stain that beat me, they believed me about the rest of the car.',
          '![My first classic Thunderbird I detailed. Ford Shelby GT500 pictured in the back.](/images/danos/thunderbird.jpg)',
          'As time went on, my detailing process began to be validated. No longer was I figuring out what chemical to use, how to close clients, and how long a typical job would take. It was how many cars a day I could physically reach.',
          'I had no money for advertising but every finished car was a billboard sitting in a driveway. The best advertising I had was the job itself and most of the work was converting attention that already existed. I planted yard signs next to the cars I worked on, which turned out to be invitations to whoever walked by. I paired this up with RFID cards that I could tap on a prospect’s phone that would pull up my website. Word of mouth became my highest-quality lead and neighbors telling each other made me the default answer when anyone in Tracy went looking for a detailer.',
          'After every completed job, I would knock on the surrounding doors and talk to homeowners with a glistening car behind me doing all the pitching. This became so effective that it led me to create my own sales team. Instead of paying for online ads, I incentivized other high schoolers to come work with me and door knock for commission. You would take home 20-25% of the sale and selling two or three services a day, a high schooler could make multiples of what they would make anywhere else. I personally trained them on how to close and taught them basic sales tactics. One of them quit after a week because door to door was too difficult.',
          '![1960’s American cars I got to work on. Not pictured: 1971 Chevelle SS, multiple 1930’s Dodge Brothers cars, and an absurd number of thunderbirds.](/images/danos/american-classics.jpg)',
          'Soon enough, this machine started producing more leads than I could serve. I had a team of door knocking salesmen, organic Google inbound, and Facebook moms all reaching out to me. I quickly had more work than I could keep up with. I started hiring my friends, paying $30 an hour with lunch included. With $17 an hour being the local wage, I had enough friends wanting to work. At the peak it was me, two to three detailers on rotation, and one to two salesmen on commission.',
          'The number of clients I was reaching increased and so did my prices. I was afraid that once I started charging professional level prices, using client’s water and electricity would affect my business. I had no water tank and used the client’s spigot on every job. I saw this as unprofessional and yet not a single client ever questioned this “problem”. With chemicals running $5 to $10 a car against the $200 to $250 I was charging, the thing I was most afraid of turned out to be the reason the margins grew.',
          'I eventually hit the real ceiling. I was already running two to four cars a day and forty to sixty jobs a month. There were only so many hours in a day and I could not grow by doing more cars.',
          '![Full detail for a Corvette c8 stingray 70th anniversary edition.](/images/danos/corvette.jpg)',
          'The best margins came from changing what I sold. Ceramic coatings, a protective polymer layer, ran $500 to $1,100 and cost me $80 in materials. Each one of these jobs required polishing experience so I began having my crew handle the daily volume, while I put my own hours on the coatings and the high ticket sales. I positioned myself as the luxury car detailer that focused on paint correction and ceramic coatings that could also tackle the toughest stains in your minivan.',
          'This dramatically increased my business revenue and I began questioning what else I could sell to a customer who already trusted me. How could I level up their experience and increase the frequency at which they sought me out?',
          'What I implemented was that after every car was detailed, you could opt into a monthly maintenance service. For $60 to $80 a month, we would show up at your driveway to keep the vehicle in mint condition. For cars that were previously ceramic coated, this was offered as a way to ensure the protection lasts. These maintenance jobs ran under an hour and made better money per hour of crew time than the flagship detail did. It also became the training grounds for every new hire.',
          '![The oldest car I detailed: Dodge Brothers 1924 Touring Car.](/images/danos/dodge-1924.jpg)',
          'What broke is that I never controlled my own calendar. I would be booked solid for an entire month and then hit a week of one or two jobs. This led me to strategize how I could fill in my dry weeks and I ended up working with dealerships. What I didn’t know was that these clients are some of the worst you can ask for. They are aggressive, stingy, and didn’t value what I spent two years building. We would agree on a predetermined price and at the time of payment, they would begin haggling their way down. Stay away from dealerships.',
          'The full weeks were also difficult. I was overbooked, jobs pushed well into the night, and the manual labor would leave my hands cramping and seizing up.',
          'I hit a breaking point on a particularly disgusting Mustang. I quoted it from photos the owner sent and priced it as a coupe that would not be difficult. When I arrived, it was far worse. There was a milkshake that had spilled and gone bad, enough trash to fill an entire bag, and I vacuumed until my hands would not open. Never again would I quote another car I had not seen in person.',
          '![The worst interior I’ve done. Spoiled milkshake and rotting food not pictured. Not my happiest memory.](/images/danos/worst-interior.jpg)',
          'There are three things I would do differently.',
          'The first is to change the fact that every call, every text, every schedule change came through me. If I had a way to collect and redirect all of the missed calls, I could have converted many leads that were lost.',
          'The second is to lean heavy into paid advertising. I felt that my outbound strategy worked well enough with the small sales team I built around it. I saw paying for online ads as an unnecessary cost. What I should’ve done is iterate fast on A/B marketing campaigns. I didn’t factor in the problem that my sales team ran on teenagers willing to walk the scorching hot streets and quit halfway.',
          'The third is to create an intake system where a customer uploads photos of their make and model. They would get a price quote back and this system would have caught jobs like the Mustang well before I ever did.',
          'I sold the catalog in January of 2025, halfway through my sophomore year at UCSD. With Tracy being seven hours away from San Diego, booking clients and working them in between quarters held for so long. My business needed someone in person and I couldn’t operate in that capacity anymore.',
          '![The dream car I detailed that inspired me to keep hustling.](/images/danos/dream-car.jpg)',
          'I took part of that check and put it into an investment thesis I had been building for months.',
          'If you have been thinking about starting something, the only step that matters is the first customer. A broke seventeen-year-old with no credibility was able to manufacture demand from nothing, and the way he did it was by solving trust. You are capable of achieving so much!',
          'I know something about going from 0 to 1. If you are in that phase or want to see some sick cars I’ve worked on, write to me. I’d love to hear what you have going on. You can message me at fezepeda@ucsd.edu!',
        ],
      },
    ],
  },
}
